### ISSUE TITLE
Segfaults when attempting to generate images 

### ISSUE THREAD

**Issue by nickr74-git** [simonlui/Docker_IPEX_ComfyUI#5]
I'm unsure if this is an issue with Comfy or this repo so if it's in the wrong place let me know. whenever I try to generate images comfy will crash. The ksampler step works fine, vae decode will freeze for several minutes and eventually seg fault. I've tried kernel 6.6.43 and 6.10 and the issue is present on both.
[dockerlog.txt](https://github.com/user-attachments/files/16520475/dockerlog.txt)

**Comment by simonlui** [comment]
Sorry, I haven't had time to look at it, I've been busy at work for the past month. This has been known since around July when I first hit it. It used to work at the time of commit, but I have only narrowed it down to the fact that the compute packages I install after the core dependencies are not at fault here. I suspect that one of the core packages in the oneAPI install is to blame but I have yet to pinpoint which one it is yet. If I get some time, I'll dig into it this weekend.

**Comment by simonlui** [comment]
@nickr74-git I was able to narrow down things this weekend but as luck would have it, Intel released a new version of IPEX yesterday. I updated the Dockerfile and it works now also so I decided to roll with the update as the fix. Can you give it a try and see if this solves the issue for you?

**Comment by nickr74-git** [comment]
Works as expected now Thank you so much for the fix.
